=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/questions.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="questions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="question" type="questionType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
            <xs:attribute name="subcategory" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="questionType">
        <xs:sequence>
            <xs:element name="line" type="xs:string"/>
            <xs:element name="hints" type="hints" minOccurs="0" maxOccurs="1"/>
            <xs:choice>
                <xs:element name="answers" type="answerMultiple"/>
                <!--<xs:element name="answer-multiple" type="answerMultiple"/>-->
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
   
    <!-- hint types -->
    <xs:complexType name="hints">  
        <xs:sequence>
            <xs:element name="hint" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="score-decrease" type="xs:integer"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="line" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                        <xs:attribute name="hints" type="xs:integer" default="7"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- answer types -->
    <xs:complexType name="answerMultiple">        
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="answer">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="required" type="xs:boolean" default="false"/>
                            <xs:attribute name="score" type="xs:integer" default="5"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="attempts" type="xs:integer" default="100"/>
        <xs:attribute name="required" type="xs:integer" default="1"/>
    </xs:complexType>

</xs:schema>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/society/law.xml
<questions
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../questions.xsd"
        category="Samhälle" subcategory="Juridik">

  <question>
    <line>Vad betyder lex lata (de lege lata)?</line>
    <answers>
      <answer>Gällande rätt</answer>
    </answers>
  </question>

  <question>
    <line>Vad innebär denuntiation?</line>
    <answers>
      <answer>Underättelse</answer>
    </answers>
  </question>

  <question>
    <line>Om någon olovligen tar 1.500 kronor från dig, men i ögonblicket han tar pengarna ångrar sig och lägger tillbaka pengarna, vilket brott har han gjorts sig skyldig?</line>
    <answers>
      <answer>Stöld</answer>
    </answers>
  </question>

  <question>
    <line>Om en domstol sägs vara inkvisitorisk innebär det att den skall...</line>
    <answers>
      <answer>Efterforska sanningen</answer>
    </answers>
  </question>

  <question>
    <line>En talan vid domstol som går ut på att domstolen skall faställa att ett visst rättsförhållande föreligger kallas?</line>
    <answers>
      <answer>Fastställelsetalan</answer>
    </answers>
  </question>

  <question>
    <line>Hur många grundlagar finns det i Sverige?</line>
    <answers>
      <answer>4 st</answer>
    </answers>
  </question>

  <question>
    <line>Nämn en av Sveriges grundlagar.</line>
    <answers>
      <answer>Tryckfrihetsförordningen</answer>
      <answer>Yttrandefrihetsgrundlagen</answer>
      <answer>Regeringsformen</answer>
      <answer>Succesionsordningen</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas det man ska ha för att låta någon handla å ens vägnar?</line>
    <answers>
      <answer>Fullmakt</answer>
    </answers>
  </question>

  <question>
    <line>Vem stiftar förordningar?</line>
    <answers>
      <answer>Regeringen</answer>
    </answers>
  </question>

  <question>
    <line>Avtal där båda parter är förpliktade av prestationer som uppväger varandra kallas?</line>
    <answers>
      <answer>Onerösa avtal</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas bland annat lagar, förordningar och föreskrifter med ett samlingsnamn?</line>
    <answers>
      <answer>Författning</answer>
    </answers>
  </question>

  <question>
    <line>Vilket är det högsta beslutande organet i ett aktiebolag?</line>
    <answers>
      <answer>Bolagsstämman</answer>
    </answers>
  </question>

  <question>
    <line>När måste den tilltalade i brottmål avge vittnesed?</line>
    <answers>
      <answer>Aldrig</answer>
    </answers>
  </question>

  <question>
    <line>Juridiken talar ofta om latinets dolus och culpa. Vad betyder de?</line>
    <answers>
      <answer>Uppsåt och vårdslöshet</answer>
    </answers>
  </question>

  <question>
    <line>Vad är lös egendom?</line>
    <answers>
      <answer>Allt som inte är fast egendom</answer>
    </answers>
  </question>

  <question>
    <line>Vad betyder kausualitet?</line>
    <answers>
      <answer>Orsakssamband</answer>
    </answers>
  </question>

  <question>
    <line>Vilken titel har en domare i Högsta domstolen?</line>
    <answers>
      <answer>Justitieråd</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den som blir stämd i ett tvistemål?</line>
    <answers>
      <answer>Svarande</answer>
    </answers>
  </question>

  <question>
    <line>Vem stiftar lagar i Sverige?</line>
    <answers>
      <answer>Riksdagen</answer>
    </answers>
  </question>

  <question>
    <line>Vilken lag förkortas PuL?</line>
    <answers>
      <answer>Personuppgiftslagen</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas förmögenhetsrättigheter som måste respekteras inte enbart av motpart utan även av tredjeman?</line>
    <answers>
      <answer>Sakrätt</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter domstolen som prövar juridiska tvister inom EU?</line>
    <answers>
      <answer>EG-domstolen</answer>
    </answers>
  </question>

  <question>
    <line>Vad betyder jura novit curia?</line>
    <answers>
      <answer>Domstolen känner lagen</answer>
    </answers>
  </question>

  <question>
    <line>Dödstraffet avskaffades i fredstid 1921 men när avskaffades dödstraffet i krigstid?</line>
    <answers>
      <answer>1973</answer>
    </answers>
  </question>

  <question>
    <line>Du har haft hantverkare hemma och får en räkning för arbetet hemskickad. På räkningen står att den ska betalas inom sju dagar. Om inget mer speciellt är avtalat, hur länge kan du vänta med att betala utan att behöva betala någon dröjsmålsränta?</line>
    <answers>
      <answer>En månad</answer>
    </answers>
  </question>

  <question>
    <line>Din sambo avlider. Ni har inga barn. Sambon har två helsyskon som närmaste släktingar. Vem ärver sambons sparade pengar (om inget testamente finns)?</line>
    <answers>
      <answer>Syskonen</answer>
    </answers>
  </question>

  <question>
    <line>Du köper en ny tv i din lokala tv- och radiobutik. Ett par dagar senare upptäcker du att en likadan tv säljs mycket billigare i en affär i närheten. Har du enligt lagen rätt att ångra ditt första köp, lämna tillbaka tvn och få pengarna tillbaka?</line>
    <answers>
      <answer>Nej</answer>
    </answers>
  </question>

  <question>
    <line>Din trettonårige son kastar sten mot en fönsterruta i skolan. Rutan går sönder. Vem är lagligen betalningsskyldig?</line>
    <answers>
      <answer>Sonen</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/medicine/konssjukdomar.xml
<questions
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="questions.xsd"
        category="Medicin" subcategory="Könssjukdomar">
 
  <question>
    <line>Vad kallas den process när man måste ange alla sina sexpartners till en kurator eller läkare, efter att ha smittats av t.ex. HIV eller gonorré?</line>
    <hints>
      <line>Partneruppföljning</line>
    </hints>
    <answers>
      <answer>Partneruppföljning</answer>
      <answer>Partnerkontroll</answer>
    </answers>
  </question>
 
  <question>
    <line>Det svider när du kissar. Det kommer en flytning från urinröret, slidan eller ändtarmen. Det gör ont i halsen. Vilken sjukdom kan du ha drabbats av?</line>
    <answers>
      <answer>Gonorré</answer>
    </answers>
  </question>

  <question>
    <line>Du mår illa. Du har minskad aptit. Du är trött. Din hud kliar. Din hud och dina ögonvitor gulfärgas. Vilken sjukdom kan du ha drabbats av?
</line>
    <answers>
      <answer>Hepatit B</answer>
    </answers>
  </question>
 
  <question>
    <line>Det är en grupp små blåsor på rodnad botten. Blåsorna bränner, kliar eller svider. De går snabbt sönder och efter några dagar läker de utan ärr. De kommer oftast runt munnen och på könsorganen men kan ibland finnas på andra ställen på kroppen. Vilken sjukdom kan du ha drabbats av?</line>
    <answers>
      <answer>Herpes</answer>
      <answer>Könsherpes</answer>
      <answer>Munherpes</answer>
    </answers>
  </question>
 
  <question>
    <line> Du har svullna lymfkörtlar. Du har svampinfektioner i munslemhinnan. Du får bältros. Du minskar kraftigt i vikt. Du hostar. Du har besvärlig och långdragen diarré. Du har kraftig nattsvettning. Du lider av svår trötthet. Vilken sjukdom kan du ha drabbats av?</line>
    <answers>
      <answer>HIV</answer>
    </answers>
  </question>
   
  <question>
    <line>Det svider när du kissar. Det kommer en flytning från urinröret, slidan eller ändtarmen. Vilken sjukdom kan du ha drabbats av?</line>
    <answers>
      <answer>Klamydia</answer>
    </answers>
  </question>
   
  <question>
    <line>Du har långsamt växande hårda vita knottror i hela underlivet. Vårtorna kan även sitta kring och i analöppningen och inne i ändtarmen. Vilken sjukdom kan du ha drabbats av?</line>
    <answers>
      <answer>Kondylom</answer>
    </answers>
  </question>
   
  <question>
    <line>Du har sår på könsorganen som inte ömmar. Du har utslag, över hela kroppen inklusive handflator och fotsulor, som inte kliar. Du har svullna ljumskar. Vilken sjukdom kan du ha drabbats av?</line>
    <answers>
      <answer>Syfilis</answer>
    </answers>
  </question>
     
  <question>
    <line>Hur behandlas gonorré?</line>
    <answers>
      <answer>Antibiotika</answer>
    </answers>
  </question>
 
    <question>
    <line>Hur behandlas Hepatit B?</line>
    <answers>
      <answer>Inte alls</answer>
    </answers>
  </question>
 
  <question>
    <line>Hur behandlas könsherpes?</line>
    <answers>
      <answer>Inte alls</answer>
    </answers>
  </question>

  <question>
    <line>Hur behandlas HIV?</line>
    <answers>
      <answer>Bromsmediciner</answer>
    </answers>
  </question>

  <question>
    <line>Hur behandlas klamydia?</line>
    <answers>
      <answer>Antibiotika</answer>
    </answers>
  </question>

  <question>
    <line>Hur behandlas kondylom?</line>
    <answers>
      <answer>Man tar bort vårtorna</answer>
      <answer>Vårtborttagning</answer>
    </answers>
  </question>
   
      <question>
    <line>Hur behandlas syfilis?</line>
    <answers>
      <answer>Antibiotika</answer>
    </answers>
  </question>

  <question>
    <line>Vilken sjukdom kan hos både kvinnor och män orsaka ögoninflammation, ledbesvär och blodförgiftning om den lämnas obehandlad?</line>
    <answers>
      <answer>Gonorré</answer>
    </answers>
  </question>

    <question>
    <line>Vilken sjukdom kan leda till skrumplever eller levercancer?</line>
    <answers>
      <answer>Hepatit B</answer>
    </answers>
  </question>

    <question>
    <line>Vilken sjukdom kan orsaka hjärnhinneinflammation eller komma in i ögats hornhinna?</line>
    <answers>
      <answer>Herpes</answer>
    </answers>
  </question>

    <question>
    <line>Vilken sjukdom leder till AIDS?</line>
    <answers>
      <answer>HIV</answer>
    </answers>
  </question>

    <question>
    <line>Vilken sjukdom kan hos både män och kvinnor orsaka ögoninflammation och ledbesvär om den lämnas obehandlas?</line>
    <answers>
      <answer>Klamydia</answer>
    </answers>
  </question>

    <question>
    <line>Vilken sjukdom kan ge skador på exempelvis hjärnan och hjärtat om den lämnas obehandlas?</line>
    <answers>
      <answer>Syfilis</answer>
    </answers>
  </question>
       
    <question>
    <line>Vad står förkortningen AIDS för?</line>
    <answers>
      <answer>Acquired Immune Deficiency Syndrome</answer>
    </answers>
  </question>
 
  <question>
    <line>Hur smittas gonorré?</line>
    <answers>
      <answer>Slemhinnekontakt</answer>
    </answers>
  </question>

  <question>
    <line>Hur smittas Hepatit B?</line>
    <hints>
      <line>Genom blod och samlag</line>
    </hints>
    <answers>
      <answer required="true">Blod</answer>
      <answer required="true">Samlag</answer>
    </answers>
  </question>

  <question>
    <line>Hur smittas könherpes?</line>
    <hints>
      <line>Genom samlag</line>
    </hints>
    <answers>
      <answer required="true">Samlag</answer>
    </answers>
  </question>
 
  <question>
    <line>Hur smittas HIV?</line>
    <hints>
      <line>Genom samlag, från en gravid kvinna till hennes foster samt genom blod eller vävnad.</line>
    </hints>
    <answers>
      <answer required="true" score="5">Samlag</answer>
      <answer required="true" score="5">gravid kvinna till hennes foster</answer>
      <answer required="true" score="5">blod</answer>
      <answer score="5">vävnad</answer>
    </answers>
  </question>
 
  <question>
    <line>Hur smittas klamydia?</line>
    <hints>
      <line>Genom samlag och oralsex</line>
    </hints>
    <answers>
      <answer required="true" score="5">Samlag</answer>
      <answer required="true" score="5">oralsex</answer>
    </answers>
  </question>
 
  <question>
    <line>Hur smittas kondylom?</line>
    <hints>
      <line>Genom samlag</line>
    </hints>
    <answers>
      <answer required="true">Samlag</answer>
    </answers>
  </question>
     
  <question>
    <line>Hur smittas syfilis?</line>
     <hints>
       <line>Genom samlag och från en gravid kvinna till hennes foster</line>
    </hints>
    <answers>
      <answer required="true" score="5">Samlag</answer>
      <answer required="true" score="5">gravid kvinna till hennes foster</answer>
    </answers>
  </question>
 
  <question>
    <line>Måste man, enligt lag, ange alla sina sexpartners om man är smittad av gonorré?</line>
    <answers attempts="1">
      <answer>Ja</answer>
    </answers>
  </question>

  <question>
    <line>Måste man, enligt lag, ange alla sina sexpartners om man är smittad av hepatit B?</line>
    <answers attempts="1">
      <answer>Ja</answer>
    </answers>
  </question>

  <question>
    <line>Måste man, enligt lag, ange alla sina sexpartners om man är smittad av herpes?</line>
    <answers attempts="1">
      <answer>Nej</answer>
    </answers>
  </question>

  <question>
    <line>Måste man, enligt lag, ange alla sina sexpartners om man är smittad av HIV?</line>
    <answers attempts="1">
      <answer>Ja</answer>
    </answers>
  </question>
 
    <question>
    <line>Måste man, enligt lag, ange alla sina sexpartners om man är smittad av klamydia?</line>
    <answers attempts="1">
      <answer>Ja</answer>
    </answers>
  </question>

    <question>
    <line>Måste man, enligt lag, ange alla sina sexpartners om man är smittad av kondylom?</line>
    <answers attempts="1">
      <answer>Nej</answer>
    </answers>
  </question>
   
    <question>
    <line>Måste man, enligt lag, ange alla sina sexpartners om man är smittad av syfilis?</line>
    <answers attempts="1">
      <answer>Ja</answer>
    </answers>
  </question>
 
  <question>
    <line>Munherpes är inte samma sorts herpesvirus som könsherpes, men kan munherpes smitta till könet via oralsex?</line>
    <answers attempts="1">
      <answer>Ja</answer>
    </answers>
  </question>
 
</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/technology/cars.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Tekink" subcategory="Motorfordon">

  <question>
    <line>Vad kallas de bilverkstäder som är auktoriserade att ta hand om vissa bilmärken?</line>
    <answers>
      <answer>Märkesverkstäder</answer>
    </answers>
  </question>
  
  <question>
    <line>Vad heter den tv-kändis i förnamn som brukar kallas Bildoktorn?</line>
    <answers>
      <answer>Bosse</answer>
    </answers>
  </question>
  
  <question>
    <line>De flesta bilar drivs på bensin. Men vad är det näst vanligaste drivmedlet?</line>
    <answers>
      <answer>Diesel</answer>
    </answers>
  </question>
  
  <question>
    <line>Var sitter motorn på en Porsche 911</line>
    <answers>
      <answer>Baktill</answer>
    </answers>
  </question>
  
  <question>
    <line>Vilken sorts däck är det förbjudet att köra med på sommaren?</line>
    <answers>
      <answer>Dubbdäck</answer>
    </answers>
  </question>
  
  <question>
    <line>Vad alstrar ett tändstift, som är nödvändigt för att motorn ska fungera?</line>
    <answers>
      <answer>Gnistor</answer>
    </answers>
  </question>
  
  <question>
    <line>Hur många takter har en vanlig bilmotor?</line>
    <hints>
      <line>4</line>
    </hints>
    <answers>
      <answer>Fyra</answer>
      <answer>4</answer>
    </answers>
  </question>
  
  <question>
    <line>Vad heter de två bröderna som är bilmekaniker i tv-serien Macken?</line>
    <hints>
      <line>Roy och Roger</line>
    </hints>
    <answers>
      <answer required="true">Roy</answer>
      <answer required="true">Roger</answer>
    </answers>
  </question>
  
  <question>
    <line>Vad heter det statliga företag som regelbundet kontrollerar bilens kondition och miljösäkerhet?</line>
    <answers>
      <answer>Bilprovningen</answer>
    </answers>
  </question>
  
  <question>
    <line>I ficklampor har man ofta alkaliska batterier. Vilken sorts batteri sitter i en bil?</line>
    <answers>
      <answer>Blybatteri</answer>
    </answers>
  </question>
  
  <question>
    <line>Nuförtiden har de flesta bilar direktinsprutning av bensinen i motorn. Vad hade man tidigare?</line>
    <answers>
      <answer>Förgasare</answer>
    </answers>
  </question>
  
  <question>
    <line>Vad heter den anordning som gör att bilen går olika fort fast man har samma varvtal i motorn?</line>
    <answers>
      <answer>Växellåda</answer>
    </answers>
  </question>
  
  <question>
    <line>En hybridbil har två motorer. En drivs med bensin. Vad drivs den andra med?</line>
    <answers>
      <answer>El</answer>
    </answers>
  </question>
  
  <question>
    <line>Förr tittade och lyssnade bilmekaniker mera efter fel i bilen. Vilket hjälpmedel används till nya bilar?</line>
    <answers>
      <answer>En dator</answer>
    </answers>
  </question>
  
  <question>
    <line>Vad kallas det ljus man har på när man kör i mörer, men måste slå av när man möter andra bilar, eftersom det bländar?</line>
    <answers>
      <answer>Helljus</answer>
    </answers>
  </question>
  
  <question>
    <line>Vad heter den anordning i bilen som laddar batteriet, och alltså alstrar ström?</line>
    <answers>
      <answer>Generator</answer>
    </answers>
  </question>
  
  <question>
    <line>>Vilka tre bokstäver brukar användas för att beteckna låsningsfria bromsar på en bil?</line>
    <answers>
      <answer>ABS</answer>
    </answers>
  </question>
  
  <question>
    <line>Ett bilhjul består av ett gummidäck och metalldel. Vad kallas metalldelen?</line>
    <answers>
      <answer>Fälg</answer>
    </answers>
  </question>
  
  <question>
    <line>Det finns två vanliga bromstyper på motorfordon. Det ena är trumbromsar. Vad kallas den andra sortens bromsar?</line>
    <answers>
      <answer>Skivbromsar</answer>
    </answers>
  </question>
  
    <question>
    <line>Vilken är den högsta hastighet en tung lastbil får hålla på svenska vägar?</line>
    <answers>
      <answer>90 km/h</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter ett företag som driver yrkesmässig lastbilstrafik?</line>
    <answers>
      <answer>Åkeri</answer>
    </answers>
  </question>

  <question>
    <line>Vilket år fick vi högertrafik i Sverige?</line>
    <answers>
      <answer>1967</answer>
    </answers>
  </question>

  <question>
    <line>Många företag sätter in en sorts spärr i sina biar, så att man inte kan köra om man har druckit alkohol. Vad kallas en sådan spärr?</line>
    <answers>
      <answer>Alkolås</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den samordning av trafiksignaler som gör att man får grönt vid flera på varandra följande korsningar?</line>
    <answers>
      <answer>Gröna vågen</answer>
    </answers>
  </question>

  <question>
    <line>Vilken bokstav måste man ha i sitt körkort för att få köra tung lastbil?</line>
    <answers>
      <answer>C</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter de tyska motorvägarna?</line>
    <answers>
      <answer>Autobahn</answer>
    </answers>
  </question>

  <question>
    <line>Hur lång får en lastbil som längst vara i Sverige?</line>
    <answers>
      <answer>24 meter</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter de två stora svenska lastbilstillverkarna?</line>
    <hints>
      <line>Scania och Volvo</line>
    </hints>
    <answers>
      <answer required="true">Scania</answer>
      <answer required="true">Volvo</answer>
    </answers>
  </question>

  <question>
    <line>Vad brukar man kalla det fenomen som medför att man underskattar sin hastighet, och alltså kör fortare än man ska?</line>
    <answers>
      <answer>Fartblindhet</answer>
    </answers>
  </question>

  <question>
    <line>Vad brukar man kalla det när lastbilschaufförer kör flera stycken i en lång rad tillsammans?</line>
    <answers>
      <answer>Konvoj</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter det statliga verk som har hand om våra vägar och deras underhåll?</line>
    <answers>
      <answer>Vägverket</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den utrustning för registrering av ett fordons användande där hastighet, vägsträcka, körtid, uppehåll och förarbyten registreras, och som ska finnas i alla yrkesfordon?</line>
    <answers>
      <answer>Färdskrivare</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas de körfält, fraför allt i storstäder, där bara buss och taxi får köra?</line>
    <answers>
      <answer>Kollektivkörfält</answer>
    </answers>
  </question>

  <question>
    <line>Vilka två färger har alltid ett påbudsmärke i trafiken, t ex ett som visar cykelväg?</line>
    <hints>
      <line>Blå botten med vit symbol</line>
    </hints>
    <answers>
      <answer>Blå botten</answer>
      <answer>vit symbol</answer>
    </answers>
  </question>

  <question>
    <line>Det har blivit vanligare på senare år att bygga små cirkulationsplatser. En del är så tånga att en buss eller lastbil har svårt att ta sig igenom. Vad kallas en cirkulationsplats också?</line>
    <answers>
      <answer>Rondell</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas med ett namn underredet med hjul och hjulupphängning på en buss, det som karossen vilar på?</line>
    <answers>
      <answer>Chassi</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas enbilolycka där bara ett fordon är inblandat?</line>
    <answers>
      <answer>Singelolycka</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas det instrument som sitter i en taxi och som beräknar kostnaden för färden?</line>
    <answers>
      <answer>Taxameter</answer>
    </answers>
  </question>
  
</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/technology/google.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="IT" subcategory="Google">

  <question>
    <line>När grundades Google Inc?</line>
    <answers>
      <answer>4 september 1998</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter Googles grundare?</line>
    <hints>
      <line>Sergey Brin och Larry Page</line>
    </hints>
    <answers>
      <answer required="true">Sergey Brin</answer>
      <answer required="true">Larry Page</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas Googles högkvarter?</line>
    <answers>
      <answer>Googleplex</answer>
    </answers>
  </question>

  <question>
    <line>Var ligger Googles högkvarter?</line>
    <hints>
      <line>I Mountain View, Kalifornien</line>
    </hints>
    <answers>
      <answer score="5">Mountain View</answer>
      <answer score="5" required="true">Kalifornien</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas Googles webbläsare som lanserades den andra september 2008?</line>
    <answers>
      <answer>Google Chrome</answer>
    </answers>
  </question>

  <question>
    <line>Vad har Googles två grundare, samt företagets nuvarnade VD, i årslön?</line>
    <hints>
      <line>1 USD</line>
    </hints>
    <answers>
      <answer>1 USD</answer>
      <answer>$1</answer>
    </answers>
  </question>

  <question>
    <line>Vad är Googles informella slogan?</line>
    <answers>
      <answer>Don't be evil</answer>
    </answers>
  </question>

  <question>
    <line>Hur mycket är en googol?</line>
    <answers>
      <answer>10^100</answer>
    </answers>
  </question>

  <question>
    <line>När börsintroducerades Google Inc?</line>
    <answers>
      <answer>19 augusti 2004</answer>
    </answers>
  </question>

</questions>
