=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/questions.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="questions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="question" type="questionType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
            <xs:attribute name="subcategory" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="questionType">
        <xs:sequence>
            <xs:element name="line" type="xs:string"/>
            <xs:element name="hints" type="hints" minOccurs="0" maxOccurs="1"/>
            <xs:choice>
                <xs:element name="answers" type="answerMultiple"/>
                <!--<xs:element name="answer-multiple" type="answerMultiple"/>-->
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
   
    <!-- hint types -->
    <xs:complexType name="hints">  
        <xs:sequence>
            <xs:element name="hint" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="score-decrease" type="xs:integer"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="line" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                        <xs:attribute name="hints" type="xs:integer" default="7"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- answer types -->
    <xs:complexType name="answerMultiple">        
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="answer">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="required" type="xs:boolean" default="false"/>
                            <xs:attribute name="score" type="xs:integer" default="5"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="attempts" type="xs:integer" default="100"/>
        <xs:attribute name="required" type="xs:integer" default="1"/>
    </xs:complexType>

</xs:schema>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/religions/greek_mythology.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Religion" subcategory="Grekisk mytologi">

  <question>
    <line>Vad kallades moder Jord i den grekiska mytologin?</line>
    <answers>
      <answer>Gaia</answer>
    </answers>
  </question>

  <question>
    <line>Vilken gudinna var Olympens drottning och Zeus syster?</line>
    <answers>
      <answer>Hera</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallades Uranos siste son som senare kom att mörda sin fader med en lie?</line>
    <answers>
      <answer>Kronos</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas de människoätande jättarna som var avkommor från Uranos och Gaia?</line>
    <answers>
      <answer>Cykloperna</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den gudinna som rövades bort och tvingades gifta sig med dödsguden Hades, vilket kom att leda till de fyra årstiderna?</line>
    <answers>
      <answer>Persefone</answer>
    </answers>
  </question>

  <question>
    <line>Vem ansvarade för att föra de dödas själar över floden Styx in i dödens rike?</line>
    <answers>
      <answer>Charon</answer>
    </answers>
  </question>

  <question>
    <line>Vem vaktar ingången till dödsriket?</line>
    <answers>
      <answer>Den trehövdade hunden Kerberos</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter jordbävningarnas och hästarnas gud enligt grekisk mytologi?</line>
    <answers>
      <answer>Poseidon</answer>
    </answers>
  </question>

  <question>
    <line>Vilket djur levde i en grotta nära Nemea och ströps av Herakles som ett av hans tolv stordåd?</line>
    <answers>
      <answer>Det nemeiska lejonet</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette Herakles hustru som av misstag dödade sin man?</line>
    <answers>
      <answer>Deianeira</answer>
    </answers>
  </question>

  <question>
    <line>Vad var Nessos för mytologisk varelse?</line>
    <answers>
      <answer>En kentaur</answer>
    </answers>
  </question>

  <question>
    <line>Var var Minos kung?</line>
    <hints>
      <line>På Kreta</line>
    </hints>
    <answers>
      <answer>På Kreta</answer>
      <answer>Kreta</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den mytologiska varelsen som i grekisk mytologi består av hälften människa och hälften tjur?</line>
    <answers>
      <answer>Minotaur</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette Herakles tvillingbror?</line>
    <answers>
      <answer>Iphikles</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallades draken som vaktade hesperidernas gyllene äpplen?</line>
    <answers>
      <answer>Ladon</answer>
    </answers>
  </question>

  <question>
    <line>Hur många huvuden har draken som vaktar hesperidernas gyllene äpplen?</line>
    <hints>
      <line>Hundra</line>
    </hints>
    <answers>
      <answer>Hundra</answer>
      <answer>100</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette den jägare som efter sin död förvandlades till en stjärnbild?</line>
    <answers>
      <answer>Orion</answer>
    </answers>
  </question>

  <question>
    <line>Vem var skådespelets gud i grekisk mytologi?</line>
    <answers>
      <answer>Dionysos</answer>
    </answers>
  </question>

  <question>
    <line>Vem var far till Zeus i Grekisk mytologi?</line>
    <answers>
      <answer>Kronos</answer>
    </answers>
  </question>

  <question>
    <line>Vem var jaktens gudinna i Grekisk mytologi?</line>
    <answers>
      <answer>Artemis</answer>
    </answers>
  </question>

  <question>
    <line>Vem förvandlade Orion till en stjärnbild?</line>
    <answers>
      <answer>Apollon</answer>
    </answers>
  </question>

  <question>
    <line>Vilka kunde, i den grekiska mytologin, förstena den som såg dem?</line>
    <answers>
      <answer>Gorgonerna</answer>
    </answers>
  </question>

  <question>
    <line>Hur dog Bellerofon?</line>
    <answers>
      <answer>Han föll av Pegasos</answer>
    </answers>
  </question>

  <question>
    <line>Vilka tre djurhuvuden hade den mytiska Chimairan?</line>
    <hints>
      <line>Lejon, get och orm</line>
    </hints>
    <answers>
      <answer required="true">lejon</answer>
      <answer required="true">get</answer>
      <answer required="true">orm</answer>
    </answers>
  </question>

  <question>
    <line>Vilken skepnad hade Zeus när han parade sig med Europa?</line>
    <answers>
      <answer>En örns</answer>
    </answers>
  </question>

  <question>
    <line>Vem sa cyklopen Polyfemos hade förblindat honom?</line>
    <answers>
      <answer>Ingen</answer>
    </answers>
  </question>

  <question>
    <line>Hur motstod Odysseus söjmän sirenernas sång?</line>
    <answers>
      <answer>De hade vax i öronen</answer>
    </answers>
  </question>

  <question>
    <line>Var sökte Odysseus Teiresias råd?</line>
    <answers>
      <answer>I dödsriket</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette malströmmen i vilken Odysseus förlorade sitt skepp och sina mannar?</line>
    <answers>
      <answer>Karybdis</answer>
    </answers>
  </question>

  <question>
    <line>Hur föddes Pegasus?</line>
    <hints>
      <line>Medusas blod blandas med havsskum</line>
    </hints>
    <answers>
      <answer>Medusas blod blandas med havsskum</answer>
      <answer>Medusas blod blandades med havsskum</answer>
</answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/culture/game_heroes.xml
<questions
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../questions.xsd"
        category="Kultur" subcategory="Tv- / Datorspelskaraktärer">

  <question>
    <line>Vad heter den gröna hjälten som vi först kom i kontakt med i spelet The Legend of Zelda?</line>
    <answers>
      <answer>Link</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter soldaten som är huvudperson i bland annat spelet Metal Gear Solid?</line>
    <answers>
      <answer>Solid Snake</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter den kvinnliga spelhjälten i spelet Metroid och Metroid Prime?</line>
    <answers>
      <answer>Samus Aran</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter, den något galna, karaktären i Baldur's Gate som ansåg att sin hamster var en superintelligent ryndvarelse?</line>
    <answers>
      <answer>Minsc</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter antihjälten i spelen God of War och God of War II?</line>
    <answers>
      <answer>Kratos</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter den något misslyckade wannabe-piraten man spelar i spelserien Monkey Island?</line>
    <answers>
      <answer>Guybrush Threepwood</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas elitsoldaten som är huvudpersonen i spelserien Halo?</line>
    <answers>
      <answer>Master Chief</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter den (ibland gröna) dinosaurieliknande figur som Mario rider på i Super Mario World?</line>
    <answers>
      <answer>Yoshi</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter spelkaraktären som man spelar i spelserien Tomb Raider?</line>
    <answers>
      <answer>Lara Croft</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter den elektriska gula pokémonfiguren som blivit något av ett varumärke för Pokémonserien?</line>
    <answers>
      <answer>Pikachu</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter hjälten med stora svärd och spetsiga hårtoppar som man först får träffa i Final Fantasy VII?</line>
    <answers>
      <answer>Cloud Strife</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter hjälten från Black Mesa som aldrig säger något under hela Half-Life-serien?</line>
    <answers>
      <answer>Gordon Freeman</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen i science ficion-spelet Deus Ex?</line>
    <answers>
      <answer>JC Denton</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen i Grand Theft Auto IV som ursprungligen kommer från Serbien?</line>
    <answers>
      <answer>Niko Bellic</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen i Final Fantasy VIII som slåss med ett så kallat gunblade?</line>
    <answers>
      <answer>Squall Leonhart</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter den spelbara karaktär som tragiskt dör i spelet Final Fantasy VII?</line>
    <answers>
      <answer>Aerith Gainsborough</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter lönnmördaren och mästerklättraren från spelet Assasin's Creed?</line>
    <answers>
      <answer>Altaïr ibn La-Ahad</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter lönnmördaren och mästerklättraren från spelet Assasin's Creed (på arabiska)?</line>
    <answers>
      <answer>الطائر ابن لا أحد</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter karaktären från Half-Life 2 som har en mekanisk hund vid namn "Dog"?</line>
    <answers>
      <answer>Alyx Vance</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen, och tillika lieman, från det humoristiska film noire-spelet Grim Fandango?</line>
    <answers>
      <answer>Manuel Calavera</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter protagonisten i Resident Evil 3 som kämpar tillsammans med Carlos Oliveira?</line>
    <answers>
      <answer>Jill Valentine</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen och tillika agenten i Tom Clancy's Splinter Cell?</line>
    <answers>
      <answer>Sam Fisher</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen som man spelar i det första Castlevania-spelet?</line>
    <answers>
      <answer>Simon Belmont</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter hjälten eller antihjälten som man spelar i Grand Theft Auto: San Andreas?</line>
    <answers>
      <answer>Carl Johnsson</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen i spelet Perfect Dark, där denne jobbar som agent för Carrington Institute?</line>
    <answers>
      <answer>Joanna Dark</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter antihjälten som man spelar i Grand Theft Auto: Vice City?</line>
    <answers>
      <answer>Thomas Vercetti</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter hjälten och blitzball-proffset från Final Fantasy X?</line>
    <answers>
      <answer>Tidus</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter huvudpersonen i spelet Tales of Symphonia?</line>
    <answers>
      <answer>Lloyd Irving</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/sport/olympic_games.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Sport" subcategory="Olympiska spelen">

  <question>
    <line>Vad hette den tjekoslovakiske löpare som 1952 tog guld i både maraton, 5000 meter, 10 000 meter?</line>
    <answers>
      <answer>Emil Zátopek</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter den tennisspelare som fullföljde sin Grand Slam med att också vinna OS-guld i Seoul 1988?</line>
    <answers>
      <answer>Steffi Graf</answer>
    </answers>
  </question>

  <question>
    <line>Vem var den svenska simmerskan som tog silver i 400 m frisim vid Rom-OS 1960?</line>
    <answers>
      <answer>Jane Cederqvist</answer>
    </answers>
  </question>

  <question>
    <line>Den australiske roddaren Henry Pearce vann guld vid Amsterdam OS 1928 trots en liten incident i mitten av hans kvartsfinal. Vad var det som hände?</line>
    <answers>
      <answer>Han stannade in för att inte köra på en ankfamilj</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette den jamaicafödde boxare som tog guld i tungviktsboxning i Moskva 1980?</line>
    <answers>
      <answer>Teófilo Stevenson</answer>
    </answers>
  </question>

  <question>
    <line>I vilken stad hölls sommarspelen 1992?</line>
    <answers>
      <answer>Barcelona</answer>
    </answers>
  </question>

  <question>
    <line>Hon tog medalj i 5 friidrottsgrenar under OS i Sydney 2000 men blev några år senare av med medljerna då hon erkände att hon varit dopad. Vad heter hon?</line>
    <answers>
      <answer>Marion Jones</answer>
    </answers>
  </question>

  <question>
    <line>1912 hölls de Olympiska spelen i Stockholm men en gren på programmet fick strykas eftersom den var förbjuden i Sverige, vilken?</line>
    <answers>
      <answer>Boxning</answer>
    </answers>
  </question>

  <question>
    <line>Konståkning stod faktiskt på programmet vid sommarspelen i London 1908. En känd svensk vars namn givit upphov till ett begrepp som fortfarande används i konståkningssammanhang vann guld. Vad hette han?</line>
    <answers>
      <answer>Ulrich Salchow</answer>
    </answers>
  </question>

  <question>
    <line>Vid OS 1984 i Los Angeles tog en rumänsk gymnast 3 guld och ett silver individuellt, men också ett lagguld. Vem var det?</line>
    <answers>
      <answer>Ecaterina Szabo</answer>
    </answers>
  </question>

  <question>
    <line>Vid OS i Sydney 2000 vann en svenska guld i lerduveskytte. Vad heter hon?</line>
    <answers>
      <answer>Pia Hansen</answer>
    </answers>
  </question>

  <question>
    <line>Hur många guld vann Jesse Owens under OS 1936?</line>
    <hints>
      <line>4 st</line>
    </hints>
    <answers>
      <answer>4 st</answer>
      <answer>fyra st</answer>
      <answer>4 stycken</answer>
      <answer>fyra stycken</answer>
    </answers>
  </question>

  <question>
    <line>I vilken stad hölls de första olympiska spelen i modern tid?</line>
    <answers>
      <answer>Aten</answer>
    </answers>
  </question>

  <question>
    <line>En 72-årig skytt var med och vann silver vid OS 1920 i Antwerpen. Han är därmed den äldsta medaljören genom tiderna. Vad hette han?</line>
    <answers>
      <answer>Oscar Swahn</answer>
    </answers>
  </question>

  <question>
    <line>I vilken gren tog Maria De Lurdes Mutola från Moçambique guld vid spelen i Sydney?</line>
    <answers>
      <answer>800 m</answer>
    </answers>
  </question>

  <question>
    <line>Vilket dopingpreparat var det kanadensaren Ben Johnson ertappades med att ha tagit vid Seoul OS 1988?</line>
    <answers>
      <answer>Stanozolol</answer>
    </answers>
  </question>

  <question>
    <line>I vilken gren tog tog Leander Paes Indiens enda medalj i Atlanta OS 1996?</line>
    <answers>
      <answer>Tennis</answer>
    </answers>
  </question>

  <question>
    <line>Sverige kom tvåa i medaljligan i Stockholm 1912 med 24 guldmedaljer. Vilket land kom etta?</line>
    <answers>
      <answer>USA</answer>
    </answers>
  </question>

  <question>
    <line>Micheline Ostermeyer från Frankrike vann både kulstötningen och diskus i London OS 1948. Vad hade hon för annan sysselsättning förutom friidrott?</line>
    <hints>
      <line>Hon var konsertpianist</line>
    </hints>
    <answers>
      <answer>Hon var konsertpianist</answer>
      <answer>konsertpianist</answer>
    </answers>
  </question>

  <question>
    <line>Bob Beamon vann längdhoppet överlägset vid Mexico OS 1968 med att sätta ett världsrekord som stod sig i 22 år. Hur långt hoppade han?</line>
    <answers>
      <answer>8,90 m</answer>
    </answers>
  </question>

  <question>
    <line>OS 1956 hölls i Melbourne men på grund av australiska karantänsbestämmelser så hölls alla ryttartävlingar i Europa. I vilken stad hölls ryttartävlingarna?</line>
    <answers>
      <answer>Stockholm</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallade USA det basketlag de skickade till OS 1992 i Barcelona bestående av bland andra Magic Johnson, Michael Jordan och Larry Bird?</line>
    <answers>
      <answer>Dream Team</answer>
    </answers>
  </question>

  <question>
    <line>Den amerikanske simmerskan Gertrude Ederle vann brons vid Paris OS 1924 i 100 meter frisim. Hon är även känd för en annan bedrift, vilken?</line>
    <answers>
      <answer>Hon var första kvinna att simma över engelska kanalen</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette den turkiske tyngdlyftare som, endast 1,47 m lång, vann guld vid Atlanta OS 1996?</line>
    <answers>
      <answer>Naim Suleymanoglu</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 2004?</line>
    <answers>
      <answer>Aten</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1988?</line>
    <hints>
      <line>Seoul</line>
    </hints>
    <answers>
      <answer>Seoul</answer>
      <answer>Söul</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 2008?</line>
    <hints>
      <line>Peking</line>
    </hints>
    <answers>
      <answer>Peking</answer>
      <answer>Bejing</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1932?</line>
    <answers>
      <answer>Los Angeles</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1964?</line>
    <answers>
      <answer>Tokyo</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1912?</line>
    <answers>
      <answer>Stockholm</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1920?</line>
    <answers>
      <answer>Antwerpen</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad skulle ha arrangerat sommarspelen 1944?</line>
    <answers>
      <answer>London</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1908?</line>
    <answers>
      <answer>London</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1948?</line>
    <answers>
      <answer>London</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1952?</line>
    <answers>
      <answer>Helsingfors</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1900?</line>
    <answers>
      <answer>Paris</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1936?</line>
    <answers>
      <answer>Berlin</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1960?</line>
    <answers>
      <answer>Rom</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1968?</line>
    <answers>
      <answer>Mexico City</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1972?</line>
    <answers>
      <answer>München</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1976?</line>
    <answers>
      <answer>Montreal</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1904?</line>
    <answers>
      <answer>St Louis</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad skulle ha arrangerat sommarspelen 1916?</line>
    <answers>
      <answer>Berlin</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1956?</line>
    <answers>
      <answer>Melbourne</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1980?</line>
    <answers>
      <answer>Moskva</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1928?</line>
    <answers>
      <answer>Amsterdam</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1984?</line>
    <answers>
      <answer>Los Angeles</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1996?</line>
    <answers>
      <answer>Atlanta</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 2000?</line>
    <answers>
      <answer>Sidney</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1924?</line>
    <answers>
      <answer>Paris</answer>
    </answers>
  </question>

  <question>
    <line>Vilken stad arrangerade sommarspelen 1896?</line>
    <answers>
      <answer>Aten</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/food_and_beverage/cocktails.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Mat och dryck" subcategory="Drinkar">

  <question>
    <line>Vad får du om du blandar 4-6cl bourbon, angostura bitter, 1 sockerbit och eventuellt soda?</line>
    <answers>
      <answer>Old fashioned</answer>
    </answers>
  </question>

  <question>
    <line>Vilken drink Innehåller 4-6cl vodka , apelsinjuice och 1cl galliano?</line>
    <answers>
      <answer>Harvey Wallbanger</answer>
    </answers>
  </question>

  <question>
    <line>Vilken drink består av 4cl bourbon, 1cl grand marnier rouge, 1cl cointreau, 1cl torr vermouth och citronskal?</line>
    <answers>
      <answer>42nd street</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter Bacardis fyra smaksatta Rom?</line>
    <hints>
      <line>Limon, Razz, Apple och Grand Melón</line>
    </hints>
    <answers>
      <answer required="true">Limon</answer>
      <answer required="true">Razz</answer>
      <answer required="true">Apple</answer>
      <answer required="true">Grand Melón</answer> 
    </answers>
  </question>

  <question>
    <line>Vad heter drinken som kallas för "välkomstdrinkens konung", och som består av gin och vermouth?</line>
    <answers>
      <answer>Dry Martini</answer>
    </answers>
  </question>

  <question>
    <line>Världens största företag inom alkoholdrycker?</line>
    <answers>
      <answer>Bacardi</answer>
    </answers>
  </question>

  <question>
    <line>Hur fick Licor 43 sitt namn?</line>
    <answers>
      <answer>Efter antalet ingredienser</answer>
    </answers>
  </question>

  <question>
    <line>Denna drink består av 4cl kanadensisk whisky (eller bourbon), 2 cl Martini Rosso och ett par stänk Angostura bitter och är en av New Yorks stadsdelar?</line>
    <answers>
      <answer>Manhattan</answer>
    </answers>
  </question>

  <question>
    <line>Vilken drink innehåller 6cl gin och 3cl lime och serveras i martiniglas?</line>
    <answers>
      <answer>Gimlet</answer>
    </answers>
  </question>

  <question>
    <line>Vilken drink blandas genom 3cl ljus rom, 2cl lime citronliqueur, 1/2 krossad apelsin och grapetonic?</line>
    <answers>
      <answer>Alegria</answer>
    </answers>
  </question>

  <question>
    <line>Var ligger merparten av tillverkningen av Absolut Vodka?</line>
    <answers>
      <answer>Åhus</answer>
    </answers>
  </question>

  <question>
    <line>Hur länge måste en cognac lagras för att få kallas en XO?</line>
    <answers>
      <answer>6 år</answer>
    </answers>
  </question>

  <question>
    <line>I filmen 'The Big Lebowski' får vi följa karaktären 'the Dude'. The Dude har en favoritdryck som består av 1 del kahlua 1.5 del vodka och en skvätt mjölk eller grädde. Vad heter drinken?</line>
    <answers>
      <answer>White Russian</answer>
    </answers>
  </question>

  <question>
    <line>En klassiker bestående av 4-6 cl vodka, några stänk worcestersås, salt, peppar, citron, några stänk tabasco och tomatjuice?</line>
    <answers>
      <answer>Bloody Mary</answer>
    </answers>
  </question>

  <question>
    <line>Vilken spritsort innehåller drinken Caipirinha?</line>
    <answers>
      <answer>Cachaça</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/culture/swedish_film.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Kultur" subcategory="Svensk film">
        
        
  <question>
    <line>Vad kallas begreppet som skapades i samband med filmer som 'Jag är nyfiken - gul' som klassades som pornografi i delar av USA?</line>
    <answers>
      <answer>Den svenska synden</answer>
    </answers>
  </question>
  
  <question>
    <line>Vem har regiserat filmen Fucking Åmål?</line>
    <answers>
      <answer>Lukas Moodyson</answer>
    </answers>
  </question>
  
  <question>
    <line>Nämn en av filmerna i Modstriologin.</line>
    <answers>
      <answer>Dom kallar oss mods</answer>
      <answer>Ett anständigt liv</answer>
      <answer>Det sociala arvet</answer>
    </answers>
  </question>

  <question>
    <line>Greta Garbo är en känd svensk skådespelare. Men vad hette hon innan hon skaffade sitt kända artistnamn?</line>
    <answers>
      <answer>Greta Gustafsson</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette skådespelaren som är känd från filmer som Söder om landsvägen och Kalle på Spången?</line>
    <answers>
      <answer>Edvard Persson</answer>
    </answers>
  </question>
  
  <question>
    <line>Vem har regiserat filmen Sånger från andra våningen?</line>
    <answers>
      <answer>Roy Andersson</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter skådespelaren som spelade mot Johnny Depp i The Ninth Gate?</line>
    <answers>
      <answer>Lena Olin</answer>
    </answers>
  </question>
  
    <question>
    <line>Vem har regiserat Utvandrarna?</line>
    <answers>
      <answer>Jan Troell</answer>
    </answers>
  </question>
  
    <question>
    <line>Vad heter Babsan på riktigt?</line>
    <answers>
      <answer>Lars-Åke Wilhelmsson</answer>
    </answers>
  </question>

</questions>
