=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/questions.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="questions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="question" type="questionType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
            <xs:attribute name="subcategory" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="questionType">
        <xs:sequence>
            <xs:element name="line" type="xs:string"/>
            <xs:element name="hints" type="hints" minOccurs="0" maxOccurs="1"/>
            <xs:choice>
                <xs:element name="answers" type="answerMultiple"/>
                <!--<xs:element name="answer-multiple" type="answerMultiple"/>-->
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
   
    <!-- hint types -->
    <xs:complexType name="hints">  
        <xs:sequence>
            <xs:element name="hint" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="score-decrease" type="xs:integer"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="line" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                        <xs:attribute name="hints" type="xs:integer" default="7"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- answer types -->
    <xs:complexType name="answerMultiple">        
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="answer">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="required" type="xs:boolean" default="false"/>
                            <xs:attribute name="score" type="xs:integer" default="5"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="attempts" type="xs:integer" default="100"/>
        <xs:attribute name="required" type="xs:integer" default="1"/>
    </xs:complexType>

</xs:schema>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/medicine/misc.xml
<questions
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../questions.xsd"
        category="Naturvetenskap" subcategory="Medicin">

  <question>
    <line>Vad är den medicinska termen som beskriver rädslan för långa ord?</line>
    <answers>
      <answer>Hippopotomonstrosesquippedaliofobi</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den psykiska sjukdom som innebär att en person medvetet gör sitt barn sjukt med syftet att sedan få vårda det?</line>
    <answers>
      <answer>Münchhausens syndrom by proxy</answer>
    </answers>
  </question>

  <question>
    <line>Vad innehåller Alvedon och Panodil för smärlindrande ämne?</line>
    <answers>
      <answer>Paracetamol</answer>
    </answers>
  </question>

  <question>
    <line>Vad innehålkler Ipren för smärtlindrande ämne?</line>
    <answers>
      <answer>Ibuprofen</answer>
    </answers>
  </question>

  <question>
    <line>Vad innehåller Magnecyl och Treo för verksamt ämne?</line>
    <answers>
      <answer>Acetylsalicylsyra</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/culture/swedish_lyrics.xml
<questions 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="questions.xsd"
    category="Kultur" subcategory="Svenska låttexter">

  <question>
    <line>I vilken låt återfinns textraden "Allt är försent, försent för vin, för sent för kärlek, ren som snö"?</line>
    <answers>
      <answer>För sent för Edelweiss</answer>
    </answers>
  </question>

  <question>
    <line>Vem sjöng textraden "Någon dag är jag din jakttrofé som du övergav"? Vi söker både låttitel och artist.</line>
    <hints>
      <line>Håkan Hellström med För en lång lång tid</line>
    </hints>
    <answers>
      <answer required="true">För en lång lång tid</answer>
      <answer required="true">Håkan Hellström</answer>
    </answers>
  </question>
  
  <question>
    <line>I vilken låt återfinns textraden "Bakom femton dubbla reglar, bakom femton dubbla lås, håller rikedomen hov i maktens salar"?</line>
    <answers>
      <answer>Keops pyramid</answer>
    </answers>
  </question>  

  <question>
    <line>I vilken låt återfinns textraden "Jag skulle unna mig och drömma, hundra mil genom Europa, om en främling lika tillitsfull som du"?</line>
    <answers>
      <answer>Om du lämnar mig nu</answer>
    </answers>
  </question>  
  
  <question>
    <line>Vem sjöng textraden "Du har så svårt att säga om jag ens betyder nåt för dig. Jag räcker inte fram."? Vi söker både låttitel och artist.</line>
    <hints>
      <line>Lars Winnerbäck med En svår och jobbig grej</line>
    </hints>
    <answers>
      <answer required="true">En svår och jobbig grej</answer>
      <answer required="true">Lars Winnerbäck</answer>
    </answers>
  </question>

  <question>
    <line>I vilken låt återfinns textraden "Ropa ner i gränden, högt så han hör. Ropa att en kärlek är inget man förgör."?</line>
    <answers>
      <answer>Öppna upp ditt fönster</answer>
    </answers>
  </question>  

  <question>
    <line>Mimikry skrev en låt där man kan höra texten "Jag är borta vid hörnan igen. Sitter och väntar när gonggongen klämtar." Vi söker låttitlen och minst en av bandets medlemar.</line>
    <answers required="2">
      <answer required="true">Nian</answer>
      <answer>Hjalle Östman</answer>
      <answer>Mia Mästerbo</answer>
      <answer>Anders Andersson</answer>
      <answer>Bror Jonas Stentäpp</answer>            
      <answer>Johan Åsberg</answer>
    </answers>
  </question>  

  <question>
    <line>I vilken låt återfinns textraden "Dom som äger framtiden är dom som köpt historien, tror du dom frågar; om du vill ha alternativ, om du vill ha ett rägligt liv efter förmåga?"? Vi söker dessutom bandets namn</line>
    <hints>
      <line>Charta 77 med Herrarna i sandlådan</line>
    </hints>    
    <answers>
      <answer required="true">Herrarna i sandlådan</answer>
      <answer required="true">Charta 77</answer>
    </answers>
  </question>  

  <question>
    <line>I vilken låt återfinns textraden "Den där skogen, gör nånting med mig - jag blir alldeles för ärlig"? Vi söker dessutom artisten.</line>
    <hints>
      <line>Säkert! med Det kommer bara leda till nåt ont</line>
    </hints>    
    <answers>
      <answer required="true">Det kommer bara leda till nåt ont</answer>
      <answer required="true">Säkert!</answer>
    </answers>
  </question>  

  <question>
    <line>I vilken låt återfinns textraden "Du vet var det sitter och siktar tills du riktigt säkert vet att det hittar in - där ingen annan kommit in"? Vi söker dessutom artisten.</line>
    <hints>
      <line>Markus Krunegård med Jag är en vampyr</line>
    </hints>    
    <answers>
      <answer required="true">Jag är en vampyr</answer>
      <answer required="true">Markus Krunegård</answer>
    </answers>
  </question>  

  <question>
    <line>I vilken låt återfinns textraden "Nere på tunnelbaneperrongen bromsar sista tåget in och kanske hinner jag ifatt, kanske jagar också du ett tåg i London, kanske inte, men kanske kan vi drömma om varandra i natt"? Vi söker dessutom artisten.</line>
    <hints>
      <line>Peggy Lejonhjärta med Sista styverns trappor</line>
    </hints>    
    <answers>
      <answer required="true">Peggy Lejonhjärta</answer>
      <answer required="true">Sista styverns trappor</answer>
    </answers>
  </question>  

  <question>
    <line>I vilken låt återfinns textraden "Var har du varit i hela mitt liv eller under hela min kväll. Under klänningen tar hon små kliv, hon kliver närmre och närmre mig."? Vi söker dessutom artisten.</line>
    <hints>
      <line>Jakob Hellman med Du är allt jag vill ha</line>
    </hints>    
    <answers>
      <answer required="true">Jakob Hellman</answer>
      <answer required="true">Du är allt jag vill ha</answer>
    </answers>
  </question>  

  <question>
    <line>I vilken låt återfinns textraden "Jag gör om alla söndagar till lördag i kväll och klär mig för att gå på kalas"? Vi söker dessutom artisten.</line>
    <hints>
      <line>Joakim Thåström med Flicka med guld...</line>
    </hints>    
    <answers>
      <answer required="true">Joakim Thåström</answer>
      <answer required="true">Flicka med guld</answer>
    </answers>
  </question>

  <question>
    <line>I vilken låt återfinns textraden "Jag tror det här är sista natten jag ser hur mörkret faller emot mig i en värld som dimmar ner, i en stad som tänder upp så långt man ser"? Vi söker dessutom artisten.</line>
    <hints>
      <line>Tomas Andersson Wij med En sommar på speed</line>
    </hints>    
    <answers>
      <answer required="true">Tomas Andersson Wij</answer>
      <answer required="true">En sommar på speed</answer>
    </answers>
  </question>

  <question>
    <line>I en av Kents låtar återfinns textraden "Långsamt glömmer man bort allt, också pojkar i manchestertyg. Men jag minns våra skrikiga stolar i köket och virveln på min kula av porslin". Vad heter låten och från vilket album är den?</line>
    <hints>
      <line>Frank från skivan Kent</line>
    </hints>    
    <answers>
      <answer required="true">Frank</answer>
      <answer required="true">Kent</answer>
    </answers>
  </question>

  <question>
    <line>I en av Kents låtar återfinns textraden "Brinn pengar brinn, jag vet att du är värd någonting. Du är hoppet i ett IQ-fritt land, du är drömmarna jag drömmer ibland.". Vad heter låten och från vilket album är den?</line>
    <hints>
      <line>Kärleken väntar från skivan Vapen &amp; ammunition</line>
    </hints>    
    <answers>
      <answer required="true">Kärleken väntar</answer>
      <answer required="true">Vapen &amp; ammunition</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/food_and_beverage/taste_descriptions.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Mat och dryck" subcategory="Öl- och spritsmaker">

 <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Kryddig smak med beska och tydlig karaktär av malört, inslag av pomerans och kanel."</line>
  <hints>
    <line>Bäska droppar</line>
  </hints>
  <answers>
   <answer score="5">Bäska droppar</answer>
   <answer score="2">Bäsk</answer>
  </answers>
 </question>

 <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Ren smak med tydlig karaktär av kummin, anis och fänkål, inslag av fat."</line>
  <hints>
    <line>OP Anderson Aquavit</line>
  </hints>
  <answers>
   <answer score="3" required="true">OP Anderson</answer>
   <answer score="2">Aquavit</answer>
  </answers>
 </question>

 <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Maltig smak med inslag av knäckebröd, honung och apelsinskal."</line>
  <hints>
   <line>Carlsberg Export</line>
  </hints>
  <answers>
   <answer>Carlsberg Export</answer>
  </answers>
 </question>

 <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Fruktig smak med inslag av ljust bröd, honung, örter och citrus."</line>
  <hints>
   <line>Pripps Blå</line>
  </hints>
  <answers>
   <answer>Pripps Blå</answer>
  </answers>
 </question>

 <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Söt, kryddig smak med viss bitterhet, inslag av lakritsrot, torkade örter, kanel, ingefära och pomerans."</line>
  <hints>
   <line>Jägermeister</line>
  </hints>
  <answers>
   <answer>Jägermeister</answer>
  </answers>
 </question>

 <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Medelstor beska. Mycket eldig, kraftfull smak med inslag av torkad frukt och nötter. Markerad efterbeska."</line>
  <hints>
   <line>Arboga 10,2</line>
  </hints>
  <answers>
   <answer>Arboga 10,2</answer>
  </answers>
 </question>

 <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Fruktig smak med liten sötma, inslag av fat, smörkola, vanilj och torkad frukt."</line>
  <hints>
   <line>Innis &amp; Gunn</line>
  </hints>
  <answers>
   <answer>Innis &amp; Gunn</answer>
   <answer>Innis and Gunn</answer>
  </answers>
 </question>

  <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Mycket söt, simmig smak med tydlig karaktär arrak, inslag av pomerans."</line>
  <hints>
   <line>Carlshamns Flaggpunsch</line>
  </hints>
  <answers>
   <answer>Carlshamns Flaggpunsch</answer>
  </answers>
 </question>

   <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Kryddig smak med inslag av arrak, mörk choklad, mandelmassa och vanilj."</line>
  <hints>
   <line>Captain Morgan Spiced Gold</line>
  </hints>
  <answers>
   <answer score="3" required="true">Captain Morgan</answer>
   <answer score="2">Spiced Gold</answer>
  </answers>
 </question>

  <question>
  <line>Vilken alkoholhaltig dryck åsyftas? "Smakrik, tydligt rostad smak med stor beska, inslag av kaffe, choklad, tjära och mörkt bröd."</line>
  <hints>
   <line>Guinness Extra Stout</line>
  </hints>
  <answers>
   <answer score="3" required="true">Guinness</answer>
   <answer score="2">Extra Stout</answer>
  </answers>
 </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/food_and_beverage/whiskey.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Mat och dryck" subcategory="Whiskey">

  <question>
    <line>Vilka ingredienser finns i whiskey?</line>
    <hints>
      <line>Säd, jäst och vatten</line>
    </hints>
    <answers>
      <answer required="true">Säd</answer>
      <answer required="true">jäst</answer>
      <answer required="true">vatten</answer>
    </answers>
  </question>

  <question>
    <line>Hur lagras whiskey innan den säljs? (undantaget Bourbon whiskey)</line>
    <answers>
      <answer>På ekfat i minst 3 år</answer>
    </answers>
  </question>

  <question>
    <line>Vad har den skotska whiskyn "Cutty Sark" på sin etikett</line>
    <answers>
      <answer>En segelbåt</answer>
    </answers>
  </question>

  <question>
    <line>Vilken amerikansk stat kommer Jack Daniels ifrån?</line>
    <answers>
      <answer>Tennessee</answer>
    </answers>
  </question>

  <question>
    <line>Vilket land kommer John Jameson från?</line>
    <answers>
      <answer>Irland</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/food_and_beverage/crisps.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Mat och dryck" subcategory="Chips">

  <question>
    <line>Estrella och OLW är störst på den svenska chipsmarknaden. Vilket märke kommer på tredje plats?</line>
    <answers>
      <answer>Pringles</answer>
    </answers>
  </question>

  <question>
    <line>Vad betyder ordet ESTRELLA?</line>
    <answers>
      <answer>Stjärna</answer>
    </answers>
  </question>

  <question>
    <line>Vilket år gjordes de första chipsen?</line>
    <answers>
      <answer>1853</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter potatischips i England?</line>
    <answers>
      <answer>Crisps</answer>
    </answers>
  </question>

  <question>
    <line>Vad betyder OLW?</line>
    <answers>
      <answer>Old London Wasa</answer>
    </answers>
  </question>

  <question>
    <line>Hur mycket potatis går det åt till ett kilo chips?</line>
    <hints>
      <line>Ca 4 kilo</line>
    </hints>
    <answers required="2">
      <answer required="true">4 kilo</answer>
      <answer>ca</answer>
      <answer>ungefär</answer>
      <answer>cirka</answer>
    </answers>
  </question>

  <question>
    <line>Hur lyder OLW:s reklamslogan?</line>
    <answers>
      <answer>Har ni fest, eller?</answer>
    </answers>
  </question>

  <question>
    <line>Hur lyder Estrellas slogan?</line>
    <answers>
      <answer>Ett lätt sätt att umgås</answer>
    </answers>
  </question>

  <question>
    <line>Vilken sorts chips äter vi mest av i Sverige?</line>
    <answers>
      <answer>Sourcream/Onion-chips</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/society/economics.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Samhälle" subcategory="Ekonomi">

  <question>
    <line>Om ett företag kombinerar sina konkurrensmedel kan försäljningen bli högre än om företaget använt konkurrensmedlen var för sig. Vad kallas denna effekt?</line>
    <answers>
      <answer>Synergieffekt</answer>
    </answers>
  </question>

  <question>
    <line>Hur många ägare kan det som lägst vara i ett aktiebolag?</line>
    <hints>
      <line>1</line>
    </hints>
    <answers>
      <answer>1</answer>
      <answer>en</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/society/Ismer.xml
<questions 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../questions.xsd" 
        category="Samhälle" subcategory="Ismer">

  <question>
    <line>Vad kallas uppfattningen om att det endast finns en gud?</line>
    <answers>
      <answer>Monoteism</answer>
    </answers>
  </question>

  <question>
    <line>Vilken politisk riktning har som syfte att avskaffa statsmakten?</line>
    <answers>
      <answer>Anarkism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kalls den lite udda avantgardistiska konstinrikningen inom modernismen?</line>
    <answers>
      <answer>Dadaism</answer>
    </answers>
  </question>

  <question>
    <line>Vilken realsocialistisk form som var tidigare vanlig i Sovjetunionen?</line>
    <answers>
      <answer>Stalinism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas det när man driver ut onda andar?</line>
    <answers>
      <answer>Exorcism</answer>
    </answers>
  </question>

  <question>
    <line>Kan kamratuppfostran också kallas?</line>
    <answers>
      <answer>Pennalism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas tron på att världen har tillkommit på övernaturlig väg?</line>
    <answers>
      <answer>Kreationism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den abstrakta konststil som skapades på 1900-talet av bland annat Pablo Picasso?</line>
    <answers>
      <answer>Kubism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kan överdriven och fanatisk patriotism också kallas?</line>
    <answers>
      <answer>Chauvinism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kan inställningen att män är överlägsna kvinnor kallas?</line>
    <answers>
      <answer>Manschauvinism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas religionen som sägs vara grundad av Siddhartha Gautama?</line>
    <answers>
      <answer>Buddhism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas blottning med ett annat ord?</line>
    <answers>
      <answer>Exhibitionism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den sexuella läggning där en person får sexuell njutning av smärta?</line>
    <answers>
      <answer>Masochism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas idéen att alla egendommar i ett samhälle bör vara gemensamt ägda?</line>
    <answers>
      <answer>Kommunism</answer>
    </answers>
  </question>

  <question>
    <line>Vad är benämningen för verksamhet som omfattar människors aktivitet när de reser till andra platser?</line>
    <answers>
      <answer>Turism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kan könsrassism kallas med annat ord?</line>
    <answers>
      <answer>Sexism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas uppfattningen att det finns flera gudar?</line>
    <answers>
      <answer>Polyteism</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den sexuella läggning som sägs vara uppkallad efter Markis Donatien Alphonse François?</line>
    <answers>
      <answer>Sadism</answer>
    </answers>
  </question>

</questions>

=== esialb/silvertrout-mavenized/src/main/resources/silvertrout/plugins/quizmaster/Questions/society/crimes.xml
<questions
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../questions.xsd"
        category="Samhälle" subcategory="Kända svenska brott">

  <question>
    <line>Under vilket namn är mannen som bara lyckades döda 1 person under totalt 10 vapenattacker mot 11 personer i Stockolmområdet 1991 - 1992 känd?</line>
    <answers>
      <answer>Lasermannen</answer>
    </answers>
  </question>

  <question>
    <line>Vad hette prästen och kyrkoherden som dödade tre personer 1864 genom att blanda arsenik i nattvardsvinet?</line>
    <answers>
      <answer>Anders Lindbäck</answer>
    </answers>
  </question>

  <question>
    <line>Var skedde natten till den 17 maj år 1900 det Svenska massmordet där fem personer dödades?</line>
    <answers>
      <answer>På en ångbåt</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas de mord där poliserna Olov Borén och Robert Karlström sköts till döds?</line>
    <answers>
      <answer>Malexandermorden</answer>
    </answers>
  </question>

  <question>
    <line>Vilken känd person sköts till döds i Sverige den 28 februari 1986?</line>
    <answers>
      <answer>Olof Palme</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallades det rånargäng som under femton månader 1985 - 1986 begick ett 20-tal rån och kom över mer än fyra miljoner kronor?</line>
    <answers>
      <answer>Maskeradligan</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den mycket medialt uppmärksammade bolagspludringen som inträffade 1997 i Sverige?</line>
    <answers>
      <answer>Trustorhärvan</answer>
    </answers>
  </question>

  <question>
    <line>Vilken känd svensk företagsledare kidnappades och återfanns senare den 3 februari i Slottsskogen i Göteborg?</line>
    <answers>
      <answer>Fabian Bengtsson</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallades den kriminella organisation som ägnade sig åt smugling i slutet av 1970-talet och början av 1980-talet och som leddes av Kivork Vartanian?</line>
    <answers>
      <answer>Skomakarligan</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallades i folkmun den division som bland annat omhändertog Osmo Vallo och enligt flera källor misshandlade denne till döds?</line>
    <answers>
      <answer>Basebolligan</answer>
    </answers>
  </question>

  <question>
    <line>Var utspelade sig mordet som hade anknytning till en filadelfiaförsamlingen och inträffade under våren 2004?</line>
    <answers>
      <answer>Knutby</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den typ av kupp där man, som exempelvis rånet mot Moderna muséet 1993 där verk av bl a Pablo Picasso stals, kommer in genom ett hål i taket?</line>
    <answers>
      <answer>Rififikupp</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas det psykologiska tillstånd som psykiatern Nils Bejerot namngav efter det berömda Norrmalmstorgsdramat 1973?</line>
    <answers>
      <answer>Stockholmsyndromet</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallades Rolf Johansson som växte upp utanför Tumba i Stockholm och som blev utnämnd till landets farligaste förbrytare?</line>
    <answers>
      <answer>Tumba-Tarzan</answer>
    </answers>
  </question>

  <question>
    <line>Vad heter juristen som är huvudmisstänkt i Trustorhärvan och som 2004 släpte boken 'Internationellt efterlyst - mitt liv efter Trustor'?</line>
    <answers>
      <answer>Joachim Posener</answer>
    </answers>
  </question>

  <question>
    <line>Vad kallas den våldtäktsman som under flera år i slutet av 90-talet och början av 2000 våldtog minst sex kvinnor i Umeå-trakten?</line>
    <answers>
      <answer>Hagamannen</answer>
    </answers>
  </question>

</questions>
